#!/bin/bash
#
# ./link-create - Cria uma simulação de instalação pelo packagist
#
# Este programa cria uma simulação temporária de instalação do pacote via packagist
#
# ATENÇÃO: esse script é exclusivo para utilizar no diretório do projeto docmap

if [ -L "vendor/bin/docmap" ]; then
    exit 0
fi


echo "Cria a simulação de pacote"

# simula a instalacao do pacote
mkdir -p vendor/iquety/docmap
cp -Rf src vendor/iquety/docmap/
cp -f docmap vendor/iquety/docmap/docmap

# gera o link simbólico
cd vendor/bin
ln -s ../iquety/docmap/docmap .
cd -

exit 0
